import type { Metadata } from "next"
import { Geist, Geist_Mono, Roboto, Playfair_Display, Sacramento, Montserrat, Tangerine, Clicker_Script } from "next/font/google"
import "./globals.css"
import { ThemeProvider } from "@/components/ThemeProvider"
import Navbar from "@/components/Navigation"
import Footer from "@/components/Footer"
import 'boxicons/css/boxicons.min.css';



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

// New fonts
const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: ["400", "700"], // choose weights you need
})

const playfair = Playfair_Display({
  variable: "--font-playfair",
  subsets: ["latin"],
})

// Sacramento
const sacramento = Sacramento({
  variable: "--font-sacramento",
  subsets: ["latin"],
  weight: "400", // Sacramento only has 400
})

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
  weight: ["400", "500", "700"], // pick weights you need
})
const tangerine = Tangerine({
  weight: ["400", "700"],
  subsets: ["latin"],
  variable: "--font-tangerine",
});
const clickerScript = Clicker_Script({
  weight: ["400"], // Clicker Script only has 400 weight
  subsets: ["latin"],
  variable: "--font-clicker-script",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`
          ${geistSans.variable} 
          ${geistMono.variable} 
          ${roboto.variable} 
          ${playfair.variable} 
          ${sacramento.variable} 
          ${montserrat.variable} 
          ${tangerine.variable}
           ${clickerScript.variable}
          antialiased
        `}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Navbar />
          {children}
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  )
}
